delete from GENRE;
delete from ALBUM;

INSERT INTO GENRE (name, description) VALUES 
	('Rock', 'Rock and Roll is a form of rock music developed in the 1950s and 1960s. Rock music combines many kinds of music from the United States, such as country music, folk music, church music, work songs, blues and jazz.'),
	('Jazz', 'Jazz is a type of music which was invented in the United States. Jazz music combines African-American music with European music. Some common jazz instruments include the saxophone, trumpet, piano, double bass, and drums.'),
	('Alternative', 'Alternative rock is a type of rock music that became popular in the 1980s and became widely popular in the 1990s. Alternative rock is made up of various subgenres that have come out of the indie music scene since the 1980s, such as grunge, indie rock, Britpop, gothic rock, and indie pop. These genres are sorted by their collective types of punk, which laid the groundwork for alternative music in the 1970s.'),
	('Metal', 'Heavy Metal is a loud, aggressive style of Rock music. The bands who play heavy-metal music usually have one or two guitars, a bass guitar and drums. In some bands, electronic keyboards, organs, or other instruments are used. Heavy metal songs are loud and powerful-sounding, and have strong rhythms that are repeated. There are many different types of Heavy Metal, some of which are described below. Heavy metal bands sometimes dress in jeans, leather jackets, and leather boots, and have long hair. Heavy metal bands sometimes behave in a dramatic way when they play their instruments or sing. However, many heavy metal bands do not like to do this.'),
	('Disco', 'Disco is a style of pop music that was popular in the mid-1970s. Disco music has a strong beat that people can dance to. People usually dance to disco music at bars called disco clubs. The word "disco" is also used to refer to the style of dancing that people do to disco music, or to the style of clothes that people wear to go disco dancing. Disco was at its most popular in the United States and Europe in the 1970s and early 1980s. Disco was brought into the mainstream by the hit movie Saturday Night Fever, which was released in 1977. This movie, which starred John Travolta, showed people doing disco dancing. Many radio stations played disco in the late 1970s.'),
	('Blues', 'The blues is a form of music that started in the United States during the start of the 20th century. It was started by former African slaves from spirituals, praise songs, and chants. The first blues songs were called Delta blues. These songs came from the area near the mouth of the Mississippi River.'),
	('Latin', 'Latin American music is the music of all countries in Latin America (and the Caribbean) and comes in many varieties. Latin America is home to musical styles such as the simple, rural conjunto music of northern Mexico, the sophisticated habanera of Cuba, the rhythmic sounds of the Puerto Rican plena, the symphonies of Heitor Villa-Lobos, and the simple and moving Andean flute. Music has played an important part recently in Latin America''s politics, the nueva canción movement being a prime example. Latin music is very diverse, with the only truly unifying thread being the use of Latin-derived languages, predominantly the Spanish language, the Portuguese language in Brazil, and to a lesser extent, Latin-derived creole languages, such as those found in Haiti.'),
	('Reggae', 'Reggae is a music genre first developed in Jamaica in the late 1960s. While sometimes used in a broader sense to refer to most types of Jamaican music, the term reggae more properly denotes a particular music style that originated following on the development of ska and rocksteady.'),
	('Pop', 'Pop music is a music genre that developed from the mid-1950s as a softer alternative to rock ''n'' roll and later to rock music. It has a focus on commercial recording, often oriented towards a youth market, usually through the medium of relatively short and simple love songs. While these basic elements of the genre have remained fairly constant, pop music has absorbed influences from most other forms of popular music, particularly borrowing from the development of rock music, and utilizing key technological innovations to produce new variations on existing themes.'),
	('Classical', 'Classical music is a very general term which normally refers to the standard music of countries in the Western world. It is music that has been composed by musicians who are trained in the art of writing music (composing) and written down in music notation so that other musicians can play it. Classical music can also be described as "art music" because great art (skill) is needed to compose it and to perform it well. Classical music differs from pop music because it is not made just in order to be popular for a short time or just to be a commercial success.');

INSERT INTO ALBUM (genre_id, title) VALUES 
(100,'For Those About To Rock We Salute You'),
(100,'Let There Be Rock'),
(100,'Greatest Hits'),
(100,'Misplaced Childhood'),
(100,'The Best Of Men At Work'),
(100,'Nevermind'),
(100,'Compositores'),
(100,'Bark at the Moon (Remastered)'),
(100,'Blizzard of Ozz'),
(100,'Diary of a Madman (Remastered)'),
(100,'No More Tears (Remastered)'),
(100,'Speak of the Devil'),
(100,'Walking Into Clarksdale'),
(100,'The Beast Live'),
(100,'Live On Two Legs [Live]'),
(100,'Riot Act'),
(100,'Ten'),
(100,'Vs.'),
(100,'Dark Side Of The Moon'),
(100,'New Adventures In Hi-Fi'),
(100,'Raul Seixas'),
(100,'By The Way'),
(100,'Californication'),
(100,'Retrospective I (1974-1980)'),
(100,'Maquinarama'),
(100,'O Samba Poconé'),
(100,'A-Sides'),
(100,'Core'),
(100,'[1997] Black Light Syndrome'),
(100,'Beyond Good And Evil'),
(100,'The Doors'),
(100,'The Police Greatest Hits'),
(100,'Hot Rocks 1964-1971 (Disc 1)'),
(100,'No Security'),
(100,'Voodoo Lounge'),
(100,'My Generation - The Very Best Of The Who'),
(100,'Achtung Baby'),
(100,'B-Sides 1980-1990'),
(100,'How To Dismantle An Atomic Bomb'),
(100,'Pop'),
(100,'Rattle And Hum'),
(100,'The Best Of 1980-1990'),
(100,'War'),
(100,'Zooropa'),
(100,'Diver Down'),
(100,'The Best Of Van Halen Vol. I'),
(100,'Van Halen III'),
(100,'Van Halen'),
(100,'Contraband'),
(100,'Un-Led-Ed'),
(100,'Balls to the Wall'),
(100,'Restless and Wild'),
(100,'Every Kind of Light'),
(100,'BBC Sessions [Disc 1] [Live]'),
(100,'BBC Sessions [Disc 2] [Live]'),
(100,'Coda'),
(100,'Houses Of The Holy'),
(100,'In Through The Out Door'),
(100,'IV'),
(100,'Led Zeppelin I'),
(100,'Led Zeppelin II'),
(100,'Led Zeppelin III'),
(100,'Physical Graffiti [Disc 1]'),
(100,'Physical Graffiti [Disc 2]'),
(100,'Presence'),
(100,'The Song Remains The Same (Disc 1)'),
(100,'The Song Remains The Same (Disc 2)'),
(100,'Bongo Fury'),
(100,'Big Ones'),
(100,'Jagged Little Pill'),
(100,'Facelift'),
(100,'Greatest Hits I'),
(100,'Greatest Hits II'),
(100,'News Of The World'),
(100,'Greatest Kiss'),
(100,'Unplugged [Live]'),
(100,'Into The Light'),
(100,'Come Taste The Band'),
(100,'Deep Purple In Rock'),
(100,'Fireball'),
(100,'Machine Head'),
(100,'MK III The Final Concerts [Disc 1]'),
(100,'Purpendicular'),
(100,'Slaves And Masters'),
(100,'Stormbringer'),
(100,'The Battle Rages On'),
(100,'The Final Concerts (Disc 2)'),
(100,'Santana - As Years Go By'),
(100,'Santana Live'),
(100,'Supernatural'),
(100,'Chronicle Vol. 1'),
(100,'Chronicle Vol. 2'),
(100,'Audioslave'),
(100,'King For A Day Fool For A Lifetime'),
(100,'In Your Honor [Disc 1]'),
(100,'In Your Honor [Disc 2]'),
(100,'The Colour And The Shape'),
(100,'Appetite for Destruction'),
(100,'Use Your Illusion I'),
(100,'A Matter of Life and Death'),
(100,'Brave New World'),
(100,'Fear Of The Dark'),
(100,'Live At Donington 1992 (Disc 1)'),
(100,'Live At Donington 1992 (Disc 2)'),
(100,'Rock In Rio [CD2]'),
(100,'The Number of The Beast'),
(100,'The X Factor'),
(100,'Virtual XI'),
(100,'Emergency On Planet Earth'),
(100,'Are You Experienced?'),
(100,'Surfing with the Alien (Remastered)'),
(109,'The Best of Beethoven'),
(109,'Pachelbel: Canon & Gigue'),
(109,'Bach: Goldberg Variations'),
(109,'Bach: The Cello Suites'),
(109,'Handel: The Messiah (Highlights)'),
(109,'Haydn: Symphonies 99 - 104'),
(109,'A Soprano Inspired'),
(109,'Wagner: Favourite Overtures'),
(109,'Tchaikovsky: The Nutcracker'),
(109,'The Last Night of the Proms'),
(109,'Respighi:Pines of Rome'),
(109,'Strauss: Waltzes'),
(109,'Carmina Burana'),
(109,'A Copland Celebration Vol. I'),
(109,'Bach: Toccata & Fugue in D Minor'),
(109,'Prokofiev: Symphony No.1'),
(109,'Scheherazade'),
(109,'Bach: The Brandenburg Concertos'),
(109,'Mascagni: Cavalleria Rusticana'),
(109,'Sibelius: Finlandia'),
(109,'Adams John: The Chairman Dances'),
(109,'Berlioz: Symphonie Fantastique'),
(109,'Prokofiev: Romeo & Juliet'),
(109,'English Renaissance'),
(109,'Mozart: Symphonies Nos. 40 & 41'),
(109,'SCRIABIN: Vers la flamme'),
(109,'Bartok: Violin & Viola Concertos'),
(109,'South American Getaway'),
(109,'Górecki: Symphony No. 3'),
(109,'Purcell: The Fairy Queen'),
(109,'Weill: The Seven Deadly Sins'),
(109,'Szymanowski: Piano Works Vol. 1'),
(109,'Nielsen: The Six Symphonies'),
(109,'Mozart: Chamber Music'),
(101,'The Best Of Billy Cobham'),
(101,'Quiet Songs'),
(101,'Worlds'),
(101,'Quanta Gente Veio ver--Bônus De Carnaval'),
(101,'Heart of the Night'),
(101,'Morning Dance'),
(101,'Warner 25 Anos'),
(101,'Miles Ahead'),
(101,'The Essential Miles Davis [Disc 1]'),
(101,'The Essential Miles Davis [Disc 2]'),
(101,'Outbreak'),
(101,'Blue Moods'),
(102,'Greatest Hits'),
(102,'Ace Of Spades'),
(102,'Motley Crue Greatest Hits'),
(102,'Alcohol Fueled Brewtality Live! [Disc 1]'),
(102,'Alcohol Fueled Brewtality Live! [Disc 2]'),
(102,'Tribute'),
(102,'Black Sabbath Vol. 4 (Remaster)'),
(102,'Black Sabbath'),
(102,'Mezmerize'),
(102,'Chemical Wedding'),
(102,'...And Justice For All'),
(102,'Black Album'),
(102,'Garage Inc. (Disc 1)'),
(102,'Garage Inc. (Disc 2)'),
(102,'Load'),
(102,'Master Of Puppets'),
(102,'ReLoad'),
(102,'Ride The Lightning'),
(102,'St. Anger'),
(102,'Plays Metallica By Four Cellos'),
(102,'Faceless'),
(102,'Use Your Illusion II'),
(102,'A Real Dead One'),
(102,'A Real Live One'),
(102,'Live After Death'),
(102,'No Prayer For The Dying'),
(102,'Piece Of Mind'),
(102,'Powerslave'),
(102,'Rock In Rio [CD1]'),
(102,'Rock In Rio [CD2]'),
(102,'Seventh Son of a Seventh Son'),
(102,'Somewhere in Time'),
(102,'The Number of The Beast'),
(102,'Living After Midnight'),
(103,'Cake: B-Sides and Rarities'),
(103,'Temple of the Dog'),
(103,'Carry On'),
(103,'Carried to Dust (Bonus Track Version)'),
(103,'Revelations'),
(105,'In Step'),
(105,'Live [Disc 1]'),
(105,'Live [Disc 2]'),
(105,'The Cream Of Clapton'),
(105,'Unplugged'),
(105,'Iron Maiden'),
(106,'Barulhinho Bom'),
(106,'Olodum'),
(106,'Acústico MTV'),
(106,'Arquivo II'),
(106,'Arquivo Os Paralamas Do Sucesso'),
(106,'Serie Sem Limite (Disc 1)'),
(106,'Serie Sem Limite (Disc 2)'),
(106,'Ao Vivo [IMPORT]'),
(106,'Prenda Minha'),
(106,'Sozinho Remix Ao Vivo'),
(106,'Minha Historia'),
(106,'Afrociberdelia'),
(106,'Da Lama Ao Caos'),
(106,'Na Pista'),
(106,'Duos II'),
(106,'Sambas De Enredo 2001'),
(106,'Vozes do MPB'),
(106,'Chill: Brazil (Disc 1)'),
(106,'Quanta Gente Veio Ver (Live)'),
(106,'The Best of Ed Motta'),
(106,'Elis Regina-Minha História'),
(106,'Milton Nascimento Ao Vivo'),
(106,'Minas'),
(106,'Jorge Ben Jor 25 Anos'),
(106,'Meus Momentos'),
(106,'Chill: Brazil (Disc 2)'),
(106,'Vinicius De Moraes'),
(106,'Cássia Eller - Sem Limite [Disc 1]'),
(106,'Djavan Ao Vivo - Vol. 02'),
(106,'Djavan Ao Vivo - Vol. 1'),
(106,'Unplugged'),
(106,'Deixa Entrar'),
(106,'Roda De Funk'),
(106,'Jota Quest-1995'),
(106,'Mais Do Mesmo'),
(107,'Greatest Hits'),
(107,'UB40 The Best Of - Volume Two [UK]'),
(107,'Acústico MTV [Live]'),
(107,'Cidade Negra - Hits'),
(108,'Axé Bahia 2001'),
(108,'Frank'),
(104,'Le Freak'),
(104,'MacArthur Park Suite'),
(104,'Ring My Bell');